### ISSUE TITLE
无法下载烧录

### ISSUE THREAD

**Issue by Oamains** [xangle/GD32F4xx_Example#1]
openocd -f interface/stlink-v2.cfg -f target/stm32f1x.cfg -c init -c "reset halt" -c "stm32f1x unlock 0"

可以提供以下你的jlink和openocd的target/xx.cfg文件

**Comment by mokeryes** [comment]
http://isworldend.com/2023/11/06/modern-way-developing-with-gd32/#more￼可以参考这篇文章，有什么疑问欢迎提

**Comment by Oamains** [comment]
感谢
